[project]
name = "day2assignment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mansoor", email = "mdmansoor16@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.142.2",
    "pydantic>=2.14.0",
    "requests>=2.34.2",
    "uvicorn>=0.54.0",
]

[project.scripts]
day2assignment = "day2assignment:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
